### ISSUE TITLE
Issue with Function Summary printer

### ISSUE THREAD

**Issue by fubuloubu** [trailofbits/slither#104]
Balance.sol:
```solidity
pragma solidity ^0.5.1;

contract SlitherContract
{
    uint balance;

    function get()
        public
        view
        returns (uint)
    {
        return balance;
    }

    function set(uint _balance)
        public
    {
        balance = _balance;
    }
}
```
```bash
$ slither Balance.sol --print function-summary
ERROR:root:Error in Balance.sol
ERROR:root:Traceback (most recent call last):
  File "/home/bryant/.pyenv/versions/3.6.7/envs/tob-workshop/lib/python3.6/site-packages/slither/__main__.py", line 226, in main_impl
    (results, number_contracts) = process(filename, args, detector_classes, printer_classes)
  File "/home/bryant/.pyenv/versions/3.6.7/envs/tob-workshop/lib/python3.6/site-packages/slither/__main__.py", line 37, in process
    return _process(slither, detector_classes, printer_classes)
  File "/home/bryant/.pyenv/versions/3.6.7/envs/tob-workshop/lib/python3.6/site-packages/slither/__main__.py", line 57, in _process
    slither.run_printers()  # Currently printers does not return results
  File "/home/bryant/.pyenv/versions/3.6.7/envs/tob-workshop/lib/python3.6/site-packages/slither/slither.py", line 93, in run_printers
    return [p.output(self.filename) for p in self._printers]
  File "/home/bryant/.pyenv/versions/3.6.7/envs/tob-workshop/lib/python3.6/site-packages/slither/slither.py", line 93, in <listcomp>
    return [p.output(self.filename) for p in self._printers]
  File "/home/bryant/.pyenv/versions/3.6.7/envs/tob-workshop/lib/python3.6/site-packages/slither/printers/summary/function.py", line 41, in output
    for (f_name, visi, modifiers, read, write, internal_calls, external_calls) in func_summaries:
ValueError: too many values to unpack (expected 7)
```

**Comment by montyly** [comment]
Hi @fubuloubu , thanks for the report!

I fixed it in [master](https://github.com/trailofbits/slither/tree/a860e0f96c95bebfd1c591a0bd5a238d4677547c)

**Comment by fubuloubu** [comment]
Works!
