### ISSUE TITLE
Crash on run on particular repo

### ISSUE THREAD

**Issue by mattaereal** [trailofbits/slither#110]
Will debug later to see what's happening. This is the error I'm getting on a project.
```
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/slither_analyzer-0.4.0-py3.7.egg/slither/__main__.py", line 238, in main_impl                       
    (results, number_contracts) = process_truffle(filename, args, detector_classes, printer_classes)                                         
  File "/usr/lib/python3.7/site-packages/slither_analyzer-0.4.0-py3.7.egg/slither/__main__.py", line 90, in process_truffle                  
    slither = Slither(all_contracts, args.solc, args.disable_solc_warnings, args.solc_args)                                                  
  File "/usr/lib/python3.7/site-packages/slither_analyzer-0.4.0-py3.7.egg/slither/slither.py", line 41, in __init__                          
    self._analyze_contracts()
  File "/usr/lib/python3.7/site-packages/slither_analyzer-0.4.0-py3.7.egg/slither/solc_parsing/slitherSolc.py", line 164, in _analyze_contracts
    fathers.append(self._contracts_by_id[i])
KeyError: 416
```

I'll try to address the issue later. Keep up the good work.

**Comment by disconnect3d** [comment]
@mattaereal Hey, can you provide any testcase for that (ideally a minimal crashing example but a repo or anything should be enough)?

**Comment by mattaereal** [comment]
I'm editing the issue because I found out it had nothing to do to the latest updates.

**Comment by mattaereal** [comment]
I'm closing it because it's not useful as it is, will come back with a better understanding of the issue.

Thanks!

**Comment by montyly** [comment]
Hey @mattaereal ,

For info, it might be related to a truffle bug, see: https://github.com/trailofbits/slither/wiki#keyerror-or-nonetype-error

**Comment by mattaereal** [comment]
Thanks! It may have been that, I had two contracts with the same name. Weird was that the stack trace did not show anything related to truffle. In fact, the compilation went just fine, because I did `truffle compile` by hand.
