### ISSUE TITLE
AssertionError when analyzing a return with arrays

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/slither#121]
Latest revision of Slither fails to analyze the following contract:

```
contract C {
  function f() returns(uint8[2], uint) {
    return ([0,0], 0);
  }
}
```
with this error:

```
ERROR:root:Error in ret.sol
ERROR:root:Traceback (most recent call last):
  File "/home/g/.local/lib/python3.6/site-packages/slither_analyzer-0.4.0-py3.6.egg/slither/__main__.py", line 236, in main_impl
    (results, number_contracts) = process(filename, args, detector_classes, printer_classes)
  File "/home/g/.local/lib/python3.6/site-packages/slither_analyzer-0.4.0-py3.6.egg/slither/__main__.py", line 35, in process
    slither = Slither(filename, args.solc, args.disable_solc_warnings, args.solc_args, ast)
  File "/home/g/.local/lib/python3.6/site-packages/slither_analyzer-0.4.0-py3.6.egg/slither/slither.py", line 41, in __init__
    self._analyze_contracts()
  File "/home/g/.local/lib/python3.6/site-packages/slither_analyzer-0.4.0-py3.6.egg/slither/solc_parsing/slitherSolc.py", line 191, in _analyze_contracts
    self._convert_to_slithir()
  File "/home/g/.local/lib/python3.6/site-packages/slither_analyzer-0.4.0-py3.6.egg/slither/solc_parsing/slitherSolc.py", line 317, in _convert_to_slithir
    func.convert_expression_to_slithir()
  File "/home/g/.local/lib/python3.6/site-packages/slither_analyzer-0.4.0-py3.6.egg/slither/solc_parsing/declarations/function.py", line 842, in convert_expression_to_slithir
    node.slithir_generation()
  File "/home/g/.local/lib/python3.6/site-packages/slither_analyzer-0.4.0-py3.6.egg/slither/core/cfg/node.py", line 366, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "/home/g/.local/lib/python3.6/site-packages/slither_analyzer-0.4.0-py3.6.egg/slither/slithir/convert.py", line 679, in convert_expression
    visitor = ExpressionToSlithIR(expression, node)
  File "/home/g/.local/lib/python3.6/site-packages/slither_analyzer-0.4.0-py3.6.egg/slither/visitors/slithir/expression_to_slithir.py", line 71, in __init__
    self._result.append(Return(get(self.expression)))
  File "/home/g/.local/lib/python3.6/site-packages/slither_analyzer-0.4.0-py3.6.egg/slither/slithir/operations/return_operation.py", line 22, in __init__
    assert is_valid_rvalue(value) or isinstance(value, TupleVariable)
AssertionError
```

**Comment by montyly** [comment]
It is already fixed in `dev` (I am not sure when I fixed it). `dev` will be soon merged into master
