### ISSUE TITLE
Slither crashes when analyzing an empty do-while loop

### ISSUE THREAD

**Issue by Xenomega** [trailofbits/slither#133]
The following contract will crash slither:
```
contract C {
    function f() {
        do {} while(true);
    }
}
```

Stack trace:
```
ERROR:root:Traceback (most recent call last):
  File "c:\users\vyper\documents\github\slither\slither\__main__.py", line 250, in main_impl
    (results, number_contracts) = process(filename, args, detector_classes, printer_classes)
  File "c:\users\vyper\documents\github\slither\slither\__main__.py", line 35, in process
    slither = Slither(filename, args.solc, args.disable_solc_warnings, args.solc_args, ast)
  File "c:\users\vyper\documents\github\slither\slither\slither.py", line 41, in __init__
    self._analyze_contracts()
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 206, in _analyze_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 290, in _analyze_third_part
    self._analyze_variables_modifiers_functions(contract)
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 330, in _analyze_variables_modifiers_functions
    contract.analyze_content_functions()
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\declarations\contract.py", line 360, in analyze_content_functions
    function.analyze_content()
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\declarations\function.py", line 818, in analyze_content
    self._parse_cfg(child)
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\declarations\function.py", line 614, in _parse_cfg
    self._parse_block(cfg, node)
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\declarations\function.py", line 595, in _parse_block
    node = self._parse_statement(statement, node)
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\declarations\function.py", line 525, in _parse_statement
    node = self._parse_dowhile(statement, node)
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\declarations\function.py", line 316, in _parse_dowhile
    link_nodes(node_startDoWhile, node_condition.sons[0])
IndexError: list index out of range
```

**Comment by montyly** [comment]
fixed in dev
