### ISSUE TITLE
Slither crashes when parsing hexadecimal unit denominations

### ISSUE THREAD

**Issue by Xenomega** [trailofbits/slither#134]
The following contract will crash slither:
```
contract C {
	function f() public {
		uint x = 0x07 ether;
	}
}
```

Stack trace:
```
ERROR:root:Traceback (most recent call last):
  File "c:\users\vyper\documents\github\slither\slither\__main__.py", line 250, in main_impl
    (results, number_contracts) = process(filename, args, detector_classes, printer_classes)
  File "c:\users\vyper\documents\github\slither\slither\__main__.py", line 35, in process
    slither = Slither(filename, args.solc, args.disable_solc_warnings, args.solc_args, ast)
  File "c:\users\vyper\documents\github\slither\slither\slither.py", line 41, in __init__
    self._analyze_contracts()
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 206, in _analyze_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 290, in _analyze_third_part
    self._analyze_variables_modifiers_functions(contract)
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 330, in _analyze_variables_modifiers_functions
    contract.analyze_content_functions()
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\declarations\contract.py", line 360, in analyze_content_functions
    function.analyze_content()
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\declarations\function.py", line 827, in analyze_content
    local_vars.analyze(self)
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\variables\variable_declaration.py", line 157, in analyze
    self._initial_expression = parse_expression(self._initializedNotParsed, caller_context)
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\expressions\expression_parsing.py", line 421, in parse_expression
    value = str(convert_subdenomination(value, expression['attributes']['subdenomination']))
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\expressions\expression_parsing.py", line 244, in convert_subdenomination
    value = float(value)
ValueError: could not convert string to float: '0x07'
```

**Comment by montyly** [comment]
PR merged in dev
