### ISSUE TITLE
Slither crashes when decoding certain characters

### ISSUE THREAD

**Issue by Xenomega** [trailofbits/slither#138]
The following contract will crash slither:
```
contract C
{
  // 合约
}
```

This happens when using the standard python open() and read() functions, so I imagine it is an issue of the encoding being not being set, or being set incorrectly.

Stack trace:
```
Traceback (most recent call last):
  File "c:\users\vyper\documents\github\slither\slither\__main__.py", line 250, in main_impl
    (results, number_contracts) = process(filename, args, detector_classes, printer_classes)
  File "c:\users\vyper\documents\github\slither\slither\__main__.py", line 35, in process
    slither = Slither(filename, args.solc, args.disable_solc_warnings, args.solc_args, ast)
  File "c:\users\vyper\documents\github\slither\slither\slither.py", line 39, in __init__
    self._parse_contracts_from_json(c)
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 55, in _parse_contracts_from_json
    self._parse_contracts_from_loaded_json(data_loaded, filename)
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 76, in _parse_contracts_from_loaded_json
    self._parse_source_unit(data_loaded, filename)
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 130, in _parse_source_unit
    source_code = f.read()
  File "C:\Users\Vyper\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 21: character maps to <undefined>
```

**Comment by montyly** [comment]
PR merged in dev
