### ISSUE TITLE
Slither errors when parsing ternary operator in a modifier

### ISSUE THREAD

**Issue by Xenomega** [trailofbits/slither#140]
The following contract will cause slither to error:
```
contract C {
	modifier test(address a) {
		address b = a != address(0) ? a : msg.sender;
		_;
	}
}
```

Changing the modifier to a function and removing the placeholder statement will not cause an error.

Stack trace:
```
ERROR:root:Traceback (most recent call last):
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 341, in _convert_to_slithir
    contract.convert_expression_to_slithir()
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\declarations\contract.py", line 367, in convert_expression_to_slithir
    func.generate_slithir_and_analyze()
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\declarations\function.py", line 927, in generate_slithir_and_analyze
    node.slithir_generation()
  File "c:\users\vyper\documents\github\slither\slither\core\cfg\node.py", line 506, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "c:\users\vyper\documents\github\slither\slither\slithir\convert.py", line 734, in convert_expression
    visitor = ExpressionToSlithIR(expression, node)
  File "c:\users\vyper\documents\github\slither\slither\visitors\slithir\expression_to_slithir.py", line 70, in __init__
    self._visit_expression(self.expression)
  File "c:\users\vyper\documents\github\slither\slither\visitors\expression\expression.py", line 41, in _visit_expression
    self._visit_assignement_operation(expression)
  File "c:\users\vyper\documents\github\slither\slither\visitors\expression\expression.py", line 98, in _visit_assignement_operation
    self._visit_expression(expression.expression_right)
  File "c:\users\vyper\documents\github\slither\slither\visitors\expression\expression.py", line 92, in _visit_expression
    self._post_visit(expression)
  File "c:\users\vyper\documents\github\slither\slither\visitors\expression\expression.py", line 266, in _post_visit
    self._post_conditional_expression(expression)
  File "c:\users\vyper\documents\github\slither\slither\visitors\slithir\expression_to_slithir.py", line 151, in _post_conditional_expression
    raise Exception('Ternary operator are not convertible to SlithIR {}'.format(expression))
Exception: Ternary operator are not convertible to SlithIR if a != address(0) then a else msg.sender
```

**Comment by montyly** [comment]
Fixed in dev
