### ISSUE TITLE
Slither errors when parsing ternary expression used as an array indexer

### ISSUE THREAD

**Issue by Xenomega** [trailofbits/slither#142]
The following contract will cause slither to error:
```
contract C  {
    function f(uint[] arr, bool b) public returns(uint) {
        return arr[b ? 1 : 2];
    }
}
```
Putting the result of the ternary expression into a variable and then using that to index into the array does not cause an error. 

Error:
```
ERROR:root:Traceback (most recent call last):
  File "c:\users\vyper\documents\github\slither\slither\__main__.py", line 250, in main_impl
    (results, number_contracts) = process(filename, args, detector_classes, printer_classes)
  File "c:\users\vyper\documents\github\slither\slither\__main__.py", line 35, in process
    slither = Slither(filename, args.solc, args.disable_solc_warnings, args.solc_args, ast)
  File "c:\users\vyper\documents\github\slither\slither\slither.py", line 41, in __init__
    self._analyze_contracts()
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 210, in _analyze_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 294, in _analyze_third_part
    self._analyze_variables_modifiers_functions(contract)
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 334, in _analyze_variables_modifiers_functions
    contract.analyze_content_functions()
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\declarations\contract.py", line 360, in analyze_content_functions
    function.analyze_content()
  File "c:\users\vyper\documents\github\slither\slither\solc_parsing\declarations\function.py", line 840, in analyze_content
    assert condition
AssertionError
```

This was not added under the existing issue #140 , as the error occurred in a different code path. (`slithir` vs `solc_parsing`)

**Comment by montyly** [comment]
I think we should fix all the remaining errors on ternary operations for 0.7.0

**Comment by 0xalpharush** [comment]
Closed by https://github.com/crytic/slither/pull/1650
