### ISSUE TITLE
Add support for embark

### ISSUE THREAD

**Issue by montyly** [trailofbits/slither#153]
Slither should support projects created using [embark](https://github.com/embark-framework/embark)

For more info: https://embark.status.im/docs/structure.html

**Comment by montyly** [comment]
One way to solve this issue is to create an `embark-slither` plugin, that would ask the AST to the embark API and run slither on it.

- Plugin documentation: https://embark.status.im/docs/creating_plugins.html
- Example of plugin: https://github.com/embark-framework/embark-fortune
- `embark.events.on('contracts:compiled:solc', callback);` contains the AST information

In the future, it would be possible to add slither as a tab to the web interface, and have the results showed and updated at each compilation

**Comment by alaibe** [comment]
Hello,

I have started to create the `embark-slither` plugin.
I am running into an issue when using the `--solc-ast`
Could you please provide an example on how to use it as well as an ast file example?

Here is my error:
```
slither .embark/contracts/simple_storage.sol.ast.json --solc-ast                                    
ERROR:root:Error in .embark/contracts/simple_storage.sol.ast.json
ERROR:root:Traceback (most recent call last):
  File "/home/anthony/.asdf/installs/python/3.6.5/lib/python3.6/site-packages/slither/__main__.py", line 250, in main_impl
    (results, number_contracts) = process(filename, args, detector_classes, printer_classes)
  File "/home/anthony/.asdf/installs/python/3.6.5/lib/python3.6/site-packages/slither/__main__.py", line 35, in process
    slither = Slither(filename, args.solc, args.disable_solc_warnings, args.solc_args, ast)
  File "/home/anthony/.asdf/installs/python/3.6.5/lib/python3.6/site-packages/slither/slither.py", line 39, in __init__
    self._parse_contracts_from_json(c)
  File "/home/anthony/.asdf/installs/python/3.6.5/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 44, in _parse_contracts_from_json
    self._parse_contracts_from_loaded_json(data_loaded['ast'], data_loaded['sourcePath'])
KeyError: 'ast'
```

I am using the ast generated and create a file from it that I pass to the command.
Thanks

**Comment by montyly** [comment]
Great, @alaibe , thanks for your contribution!

Could you share how you generate the json file?

Here an example of use:
```bash
$ cat test.sol 
contract Test{

}
$ solc --ast-json > test.legacy.json
$ slither test.legacy.json
INFO:Slither:test.legacy.json analyzed (1 contracts), 0 result(s) found
$ solc --ast-compact-json > test.compact.json
$ slither test.compact.json
 INFO:Slither:test.compact.json analyzed (1 contracts), 0 result(s) found
```

Notes:
- `--solc-ast` flag is optional (if the filename ends with `.json`)
- both the legacy and the compact AST are supported, though I would recommend to use the compact AST format, as it generates a cleaner tree

Are you doing any modifications on the json file generated? The crash looks like you remove the non-json part generated by solc.

**Comment by alaibe** [comment]
You can see here how I generate the AST:
https://github.com/embark-framework/embark/compare/feat/slither?expand=1
(The commented code in `index.ts`)

I feel my ast has the wrong format, here it is:
```
{
  "absolutePath": "/home/anthony/code/embark-framework/embark_demo/.embark/contracts/simpleStorage2.sol",
  "exportedSymbols": {
    "SimpleStorage2": [
      32
    ]
  },
  "id": 33,
  "nodeType": "SourceUnit",
  "nodes": [
    {
      "id": 1,
      "literals": [
        "solidity",
        "^",
        "0.5",
        ".0"
      ],
      "nodeType": "PragmaDirective",
      "src": "0:23:0"
    },
    {
      "baseContracts": [],
      "contractDependencies": [],
      "contractKind": "contract",
      "documentation": null,
      "fullyImplemented": true,
      "id": 32,
      "linearizedBaseContracts": [
        32
      ],
      "name": "SimpleStorage2",
      "nodeType": "ContractDefinition",
      "nodes": [
        {
          "constant": false,
          "id": 3,
          "name": "storedData",
          "nodeType": "VariableDeclaration",
          "scope": 32,
          "src": "53:22:0",
          "stateVariable": true,
          "storageLocation": "default",
          "typeDescriptions": {
            "typeIdentifier": "t_uint256",
            "typeString": "uint256"
          },
          "typeName": {
            "id": 2,
            "name": "uint",
            "nodeType": "ElementaryTypeName",
            "src": "53:4:0",
            "typeDescriptions": {
              "typeIdentifier": "t_uint256",
              "typeString": "uint256"
            }
          },
          "value": null,
          "visibility": "public"
        },
        {
          "body": {
            "id": 12,
            "nodeType": "Block",
            "src": "118:36:0",
            "statements": [
              {
                "expression": {
                  "argumentTypes": null,
                  "id": 10,
                  "isConstant": false,
                  "isLValue": false,
                  "isPure": false,
                  "lValueRequested": false,
                  "leftHandSide": {
                    "argumentTypes": null,
                    "id": 8,
                    "name": "storedData",
                    "nodeType": "Identifier",
                    "overloadedDeclarations": [],
                    "referencedDeclaration": 3,
                    "src": "124:10:0",
                    "typeDescriptions": {
                      "typeIdentifier": "t_uint256",
                      "typeString": "uint256"
                    }
                  },
                  "nodeType": "Assignment",
                  "operator": "=",
                  "rightHandSide": {
                    "argumentTypes": null,
                    "id": 9,
                    "name": "initialValue",
                    "nodeType": "Identifier",
                    "overloadedDeclarations": [],
                    "referencedDeclaration": 5,
                    "src": "137:12:0",
                    "typeDescriptions": {
                      "typeIdentifier": "t_uint256",
                      "typeString": "uint256"
                    }
                  },
                  "src": "124:25:0",
                  "typeDescriptions": {
                    "typeIdentifier": "t_uint256",
                    "typeString": "uint256"
                  }
                },
                "id": 11,
                "nodeType": "ExpressionStatement",
                "src": "124:25:0"
              }
            ]
          },
          "documentation": null,
          "id": 13,
          "implemented": true,
          "kind": "constructor",
          "modifiers": [],
          "name": "",
          "nodeType": "FunctionDefinition",
          "parameters": {
            "id": 6,
            "nodeType": "ParameterList",
            "parameters": [
              {
                "constant": false,
                "id": 5,
                "name": "initialValue",
                "nodeType": "VariableDeclaration",
                "scope": 13,
                "src": "92:17:0",
                "stateVariable": false,
                "storageLocation": "default",
                "typeDescriptions": {
                  "typeIdentifier": "t_uint256",
                  "typeString": "uint256"
                },
                "typeName": {
                  "id": 4,
                  "name": "uint",
                  "nodeType": "ElementaryTypeName",
                  "src": "92:4:0",
                  "typeDescriptions": {
                    "typeIdentifier": "t_uint256",
                    "typeString": "uint256"
                  }
                },
                "value": null,
                "visibility": "internal"
              }
            ],
            "src": "91:19:0"
          },
          "returnParameters": {
            "id": 7,
            "nodeType": "ParameterList",
            "parameters": [],
            "src": "118:0:0"
          },
          "scope": 32,
          "src": "80:74:0",
          "stateMutability": "nonpayable",
          "superFunction": null,
          "visibility": "public"
        },
        {
          "body": {
            "id": 22,
            "nodeType": "Block",
            "src": "186:25:0",
            "statements": [
              {
                "expression": {
                  "argumentTypes": null,
                  "id": 20,
                  "isConstant": false,
                  "isLValue": false,
                  "isPure": false,
                  "lValueRequested": false,
                  "leftHandSide": {
                    "argumentTypes": null,
                    "id": 18,
                    "name": "storedData",
                    "nodeType": "Identifier",
                    "overloadedDeclarations": [],
                    "referencedDeclaration": 3,
                    "src": "192:10:0",
                    "typeDescriptions": {
                      "typeIdentifier": "t_uint256",
                      "typeString": "uint256"
                    }
                  },
                  "nodeType": "Assignment",
                  "operator": "=",
                  "rightHandSide": {
                    "argumentTypes": null,
                    "id": 19,
                    "name": "x",
                    "nodeType": "Identifier",
                    "overloadedDeclarations": [],
                    "referencedDeclaration": 15,
                    "src": "205:1:0",
                    "typeDescriptions": {
                      "typeIdentifier": "t_uint256",
                      "typeString": "uint256"
                    }
                  },
                  "src": "192:14:0",
                  "typeDescriptions": {
                    "typeIdentifier": "t_uint256",
                    "typeString": "uint256"
                  }
                },
                "id": 21,
                "nodeType": "ExpressionStatement",
                "src": "192:14:0"
              }
            ]
          },
          "documentation": null,
          "id": 23,
          "implemented": true,
          "kind": "function",
          "modifiers": [],
          "name": "set",
          "nodeType": "FunctionDefinition",
          "parameters": {
            "id": 16,
            "nodeType": "ParameterList",
            "parameters": [
              {
                "constant": false,
                "id": 15,
                "name": "x",
                "nodeType": "VariableDeclaration",
                "scope": 23,
                "src": "171:6:0",
                "stateVariable": false,
                "storageLocation": "default",
                "typeDescriptions": {
                  "typeIdentifier": "t_uint256",
                  "typeString": "uint256"
                },
                "typeName": {
                  "id": 14,
                  "name": "uint",
                  "nodeType": "ElementaryTypeName",
                  "src": "171:4:0",
                  "typeDescriptions": {
                    "typeIdentifier": "t_uint256",
                    "typeString": "uint256"
                  }
                },
                "value": null,
                "visibility": "internal"
              }
            ],
            "src": "170:8:0"
          },
          "returnParameters": {
            "id": 17,
            "nodeType": "ParameterList",
            "parameters": [],
            "src": "186:0:0"
          },
          "scope": 32,
          "src": "158:53:0",
          "stateMutability": "nonpayable",
          "superFunction": null,
          "visibility": "public"
        },
        {
          "body": {
            "id": 30,
            "nodeType": "Block",
            "src": "264:28:0",
            "statements": [
              {
                "expression": {
                  "argumentTypes": null,
                  "id": 28,
                  "name": "storedData",
                  "nodeType": "Identifier",
                  "overloadedDeclarations": [],
                  "referencedDeclaration": 3,
                  "src": "277:10:0",
                  "typeDescriptions": {
                    "typeIdentifier": "t_uint256",
                    "typeString": "uint256"
                  }
                },
                "functionReturnParameters": 27,
                "id": 29,
                "nodeType": "Return",
                "src": "270:17:0"
              }
            ]
          },
          "documentation": null,
          "id": 31,
          "implemented": true,
          "kind": "function",
          "modifiers": [],
          "name": "get",
          "nodeType": "FunctionDefinition",
          "parameters": {
            "id": 24,
            "nodeType": "ParameterList",
            "parameters": [],
            "src": "227:2:0"
          },
          "returnParameters": {
            "id": 27,
            "nodeType": "ParameterList",
            "parameters": [
              {
                "constant": false,
                "id": 26,
                "name": "retVal",
                "nodeType": "VariableDeclaration",
                "scope": 31,
                "src": "251:11:0",
                "stateVariable": false,
                "storageLocation": "default",
                "typeDescriptions": {
                  "typeIdentifier": "t_uint256",
                  "typeString": "uint256"
                },
                "typeName": {
                  "id": 25,
                  "name": "uint",
                  "nodeType": "ElementaryTypeName",
                  "src": "251:4:0",
                  "typeDescriptions": {
                    "typeIdentifier": "t_uint256",
                    "typeString": "uint256"
                  }
                },
                "value": null,
                "visibility": "internal"
              }
            ],
            "src": "250:13:0"
          },
          "scope": 32,
          "src": "215:77:0",
          "stateMutability": "view",
          "superFunction": null,
          "visibility": "public"
        }
      ],
      "scope": 33,
      "src": "25:269:0"
    }
  ],
  "src": "0:294:0"
}%  
```

**Comment by alaibe** [comment]
Good news, after adding the non-json part, it works!!
Thanks for the hint

**Comment by montyly** [comment]
Oh great! 
Otherwise, I added the support for json files where the non-json text was removed in https://github.com/trailofbits/slither/commit/64343da44a4b80cc014de7014bcf226fd5e235b9 

Sidenote: the [json documentation](https://github.com/trailofbits/slither/wiki/JSON-output) is out of date (and don't use the latest format https://github.com/trailofbits/slither/pull/108).
I will update it today

**Comment by montyly** [comment]
I am closing this issue, @alaibe started a plugin here: https://github.com/embark-framework/embark-slither
