### ISSUE TITLE
 No module named detectors.abstract_detector

### ISSUE THREAD

**Issue by allenyang0812** [trailofbits/slither#73]
it will be error when I use the command, I have try  to solve the problem, but it is failure, Can you help me solve the problem? thanks in advance!
my os is ubuntu 16.04
root@biaoy3:~/MetaCoin/contracts# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

this is the error message. 
root@biaoy3:~/MetaCoin/contracts# slither MetaCoin.sol
Traceback (most recent call last):
  File "/usr/local/bin/slither", line 9, in <module>
    load_entry_point('slither-analyzer==0.2.0', 'console_scripts', 'slither')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/slither/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/slither/slither.py", line 6, in <module>
ImportError: No module named detectors.abstract_detector

**Comment by montyly** [comment]
Hi,
Slither requires python 3.6 (your logs show the use of python 2.7).

If I am not mistaken, Ubuntu 16.04 doesn't have python 3.6 by default, but you can install it following [these instructions](https://askubuntu.com/a/865569).

I am curious, how did you install slither with python 2.7?

**Comment by allenyang0812** [comment]
@montyly ok, thanks, I will try it again

**Comment by allenyang0812** [comment]
@montyly sorry, it is my fault, I use the unmatched python version lead to the problem.
