### ISSUE TITLE
Slither Bug: AttributeError: 'MappingType' object has no attribute 'type'

### ISSUE THREAD

**Issue by zedt3ster** [trailofbits/slither#83]
### Description

First of all, thanks to Trail of Bits for creating and maintaining this great solidity static analyser! 
Slither produces the following error messages when executed against specific solidity contracts:

```
ERROR:root:Error in Nomin.sol
ERROR:root:Traceback (most recent call last):
  File "/home/mz/.virtualenvs/test_slither/lib/python3.7/site-packages/slither/__main__.py", line 226, in main_impl
    (results, number_contracts) = process(filename, args, detector_classes, printer_classes)
  File "/home/mz/.virtualenvs/test_slither/lib/python3.7/site-packages/slither/__main__.py", line 35, in process
    slither = Slither(filename, args.solc, args.disable_solc_warnings, args.solc_args, ast)
  File "/home/mz/.virtualenvs/test_slither/lib/python3.7/site-packages/slither/slither.py", line 41, in __init__
    self._analyze_contracts()
  File "/home/mz/.virtualenvs/test_slither/lib/python3.7/site-packages/slither/solc_parsing/slitherSolc.py", line 191, in _analyze_contracts
    self._convert_to_slithir()
  File "/home/mz/.virtualenvs/test_slither/lib/python3.7/site-packages/slither/solc_parsing/slitherSolc.py", line 317, in _convert_to_slithir
    func.convert_expression_to_slithir()
  File "/home/mz/.virtualenvs/test_slither/lib/python3.7/site-packages/slither/solc_parsing/declarations/function.py", line 838, in convert_expression_to_slithir
    node.slithir_generation()
  File "/home/mz/.virtualenvs/test_slither/lib/python3.7/site-packages/slither/core/cfg/node.py", line 364, in slithir_generation
    self._find_read_write_call()
  File "/home/mz/.virtualenvs/test_slither/lib/python3.7/site-packages/slither/core/cfg/node.py", line 397, in _find_read_write_call
    self._high_level_calls.append((ir.destination.type.type, ir.function))
AttributeError: 'MappingType' object has no attribute 'type'
```

### Steps to reproduce

* Install slither 0.3 using a new python virtual environment (bug was reproduced using python 3.7.0 and 3.7.1)
* Run slither against the following contract: https://github.com/Havven/havven/tree/b3962e3d025b9087a0bef1814d9f83a69e4ff690/contracts/Nomin.sol (running slither against other contracts in that repository at that specific commit reproduces the same behaviour)
* Observe crash

**Comment by montyly** [comment]
Hi @zedt3ster, thanks for the issue!

It's fixed in `master`. Slither works on `Nomin.sol` now
