### ISSUE TITLE
AttributeError: 'ArrayType' object has no attribute 'type_to'

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/slither#99]
Slither crashes when analyzing [this contract](https://etherscan.io/address/0xb07ec2c28834b889b1ce527ca0f19364cd38935c#code):

```
ERROR:root:Error in contracts/0xb07ec2c28834b889b1ce527ca0f19364cd38935c_CardStackToken.sol
ERROR:root:Traceback (most recent call last):
  File "/home/gustavo/.local/lib/python3.6/site-packages/slither_analyzer-0.3.1-py3.6.egg/slither/__main__.py", line 226, in main_impl
    (results, number_contracts) = process(filename, args, detector_classes, printer_classes)
  File "/home/gustavo/.local/lib/python3.6/site-packages/slither_analyzer-0.3.1-py3.6.egg/slither/__main__.py", line 35, in process
    slither = Slither(filename, args.solc, args.disable_solc_warnings, args.solc_args, ast)
  File "/home/gustavo/.local/lib/python3.6/site-packages/slither_analyzer-0.3.1-py3.6.egg/slither/slither.py", line 41, in __init__
    self._analyze_contracts()
  File "/home/gustavo/.local/lib/python3.6/site-packages/slither_analyzer-0.3.1-py3.6.egg/slither/solc_parsing/slitherSolc.py", line 191, in _analyze_contracts
    self._convert_to_slithir()
  File "/home/gustavo/.local/lib/python3.6/site-packages/slither_analyzer-0.3.1-py3.6.egg/slither/solc_parsing/slitherSolc.py", line 317, in _convert_to_slithir
    func.convert_expression_to_slithir()
  File "/home/gustavo/.local/lib/python3.6/site-packages/slither_analyzer-0.3.1-py3.6.egg/slither/solc_parsing/declarations/function.py", line 838, in convert_expression_to_slithir
    node.slithir_generation()
  File "/home/gustavo/.local/lib/python3.6/site-packages/slither_analyzer-0.3.1-py3.6.egg/slither/core/cfg/node.py", line 362, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "/home/gustavo/.local/lib/python3.6/site-packages/slither_analyzer-0.3.1-py3.6.egg/slither/slithir/convert.py", line 682, in convert_expression
    result = apply_ir_heuristics(result, node)
  File "/home/gustavo/.local/lib/python3.6/site-packages/slither_analyzer-0.3.1-py3.6.egg/slither/slithir/convert.py", line 540, in apply_ir_heuristics
    irs = propage_type_and_convert_call(irs, node)
  File "/home/gustavo/.local/lib/python3.6/site-packages/slither_analyzer-0.3.1-py3.6.egg/slither/slithir/convert.py", line 156, in propage_type_and_convert_call
    new_ins = propagate_types(ins, node)
  File "/home/gustavo/.local/lib/python3.6/site-packages/slither_analyzer-0.3.1-py3.6.egg/slither/slithir/convert.py", line 421, in propagate_types
    return convert_type_of_high_level_call(ir, contract)
  File "/home/gustavo/.local/lib/python3.6/site-packages/slither_analyzer-0.3.1-py3.6.egg/slither/slithir/convert.py", line 372, in convert_type_of_high_level_call
    tmp = tmp.type_to
AttributeError: 'ArrayType' object has no attribute 'type_to'
```

**Comment by montyly** [comment]
Fixed in master [master](https://github.com/trailofbits/slither/commit/f70fe60b1d81313c764f063c0ed1f6f160364aa7)
